name: LedNet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pytorch>=1.3.0
  - torchvision
  - cudatoolkit>=9.2    # mac OS users should comment out this (for CPU only) or build from the source
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pytest
  - pip
  - pip:
    - delayed-assert
